#AIRTH MATIC OPERATOR USING USER ENTER THE VALUE

#ENTER THE TWO VARIABLE

a = int(input("enter the number"))
b = int(input("enter the number"))
c = a + b 
d = a / b
e = a * b
f = a % b
g = a - b

print ("addition :=",c)
print ("divison :=",d)
print ("multiplication :=",e)
print ("moduler :=",f)
print ("substraction :=",g)

#COMPERSION OPERATOR USING USER ENTER THE VALUE

i = int(input("enter the number"))
j = int(input("enter the number"))

print ("1)equal to",i == j)
print ("2)not equalto",i != j)
print ("3)greter than",i > j)
print ("4)less than",i < j)
print ("5)greter than equal to",i >= j)
print ("6)less than equal to ",i <= j)

#LOGICAL OPERATOR USING USER ENTER THE VALUE

'''and , or , not are used in''' 